/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        // Log pesan pada level INFO
        logger.info("Program Nimonscooked dimulai.");

        // Log pesan pada level DEBUG (hanya terlihat karena level root disetel 'debug')
        logger.debug("Mencoba memuat konfigurasi awal...");

        // Lanjutkan dengan memanggil GameManager (Langkah selanjutnya)
        GameManager.getInstance().initialize(); 
    }
}
